### PR TITLE
Fix occasional error in spikeStreamReport test

### PR DESCRIPTION
**Pull request by jafyvilla**
Use a different random port for each test case

### CODE REVIEW

**Comment by tribal-tec** [comment]
That still does not work. The random picked port might be picked as well by the same test from another CI job on the same machine...

**Comment by jafyvilla** [comment]
Forgot about this one... I'll try to finish it properly

**Comment by jafyvilla** [comment]
Now it should be ready

**Comment by tribal-tec** [comment]
+1 for me

**Comment by jafyvilla** [comment]
@eile This PR should fix the build. Waiting on https://github.com/BlueBrain/Brion/pull/25 to update Brion's sha1 and merge.

**Comment by eile** [comment]
Thanks.

**Pull request merged**
