### PR TITLE
Adapt to renaming of MUSIC package.

### PR DESCRIPTION
**Pull request by hernando**

### CODE REVIEW

**Comment by jafyvilla** [comment]
+1
CMake error on Ubuntu though

**Comment by hernando** [comment]
PythonLibs not found?!

**Comment by bilgili** [comment]
retest this please

**Comment by jafyvilla** [comment]
Retest this please

**Comment by hernando** [comment]
Retest this please

**Comment by hernando** [comment]
Retest this please

**Comment by hernando** [comment]
Retest this please

**Comment by hernando** [comment]
I have reset the bump in CMake/common. The latest version is "better" and now it's able to find boost Python 3 is available. The Python 3 interpreter is also available, but not the libraries.

**Comment by hernando** [comment]
Retest this please

**Comment by hernando** [comment]
Retest this please

**Comment by bilgili** [comment]
+1 ?

**Pull request merged**
